/**
 * Runtime Errors types
 */
export enum ErrorType {
    INSTRUCTION = "INSTRUCTION",
    INSTRUCTION_LEFT = "INSTRUCTION_LEFT",
    INSTRUCTION_FORWARD = "INSTRUCTION_FORWARD",
    INSTRUCTION_PICKBUZZER = "INSTRUCTION_PICKBUZZER",
    INSTRUCTION_LEAVEBUZZER = "INSTRUCTION_LEAVEBUZZER",
    STACK = "STACK",
    WALL = "WALL",
    WORLDUNDERFLOW = "WORLDUNDERFLOW",
    WORLDOVERFLOW = "WORLDOVERFLOW",
    BAGUNDERFLOW = "BAGUNDERFLOW",
    BAGOVERFLOW = "BAGOVERFLOW",
    INVALIDOPCODE = "INVALIDOPCODE",
    STACKMEMORY = "STACKMEMORY",
    CALLSIZE = "CALLSIZE",
    INTEGEROVERFLOW = "INTEGEROVERFLOW",
    INTEGERUNDERFLOW = "INTEGERUNDERFLOW",
}


export type ErrorLiteral = keyof typeof ErrorType;

/**
 * Runtime error codes
 */
export enum RuntimeErrorCodes {
    WALL = 16,
    WORLDUNDERFLOW = 17,
    BAGUNDERFLOW = 18,
    STACK = 19,
    STACKMEMORY = 20,
    CALLSIZE = 21,
    INTEGEROVERFLOW = 22,
    INTEGERUNDERFLOW = 23,
    WORLDOVERFLOW = 24,
    BAGOVERFLOW = 25,
    INSTRUCTION = 48,
    INSTRUCTION_LEFT = 49,
    INSTRUCTION_FORWARD = 50,
    INSTRUCTION_PICKBUZZER = 51,
    INSTRUCTION_LEAVEBUZZER = 52,
    INVALIDOPCODE = -1,
}